const champions = {
    'Champs': [
        {
            champName: 'ismail abilov',
            sport: 'wrestling',
            games: 'moscow 1980',
            img: '../pics/ismailabilov.jpg',
            all: 'all',
        },
        {
            champName: 'yordan bikov',
            sport: 'weightlifting',
            games: 'munich 1972',
            img: '../pics/yordanbikov.jpg',
            all: 'all',
        },
        {
            champName: 'tanya bogomilova',
            sport: 'swimming',
            games: 'seoul 1988',
            img: '../pics/tanyabogomilova.jpg',
            all: 'all',
        },
        {
            champName: 'galabin boevski',
            sport: 'weightlifting',
            games: 'sydney 2000',
            img: '../pics/galabinboevski.jpg',
            all: 'all',
        },
        {
            champName: 'nikolay buhalov',
            sport: 'canoe',
            games: 'barcelona 1992',
            img: '../pics/nikolaybuhalov.jpg',
            all: 'all',
        },
        {
            champName: 'enyo valchev',
            sport: 'wrestling',
            games: 'tokyo 1964',
            img: '../pics/enyovalchev.jpg',
            all: 'all',
        },
        {
            champName: 'prodan gardzhev',
            sport: 'wrestling',
            games: 'tokyo 1964',
            img: '../pics/prodangardzhev.jpg',
            all: 'all',
        },
        {
            champName: 'lyubomir geraskov',
            sport: 'gymnastics',
            games: 'seoul 1988',
            img: '../pics/lyubomirgeraskov.jpg',
            all: 'all',
        },
        {
            champName: 'vanya gesheva',
            sport: 'kayak',
            games: 'seoul 1988',
            img: '../pics/vanyagesheva.jpg',
            all: 'all',
        },
        {
            champName: 'borislav gidikov',
            sport: 'weightlifting',
            games: 'seoul 1988',
            img: '../pics/borislavgidikov.jpg',
            all: 'all',
        },
        {
            champName: 'ivet goranova',
            sport: 'karate',
            games: 'tokyo 2020',
            img: '../pics/ivetgoranova.jpg',
            all: 'all',
        },
        {
            champName: 'mariya grozdeva',
            sport: 'shooting',
            games: 'sydney 2000',
            img: '../pics/mariyagrozdeva.jpg',
            all: 'all',
        },
        {
            champName: 'mariya grozdeva',
            sport: 'shooting',
            games: 'athens 2004',
            img: '../pics/mariyagrozdeva.jpg',
            all: 'all',
        },
        {
            champName: 'stoyanka gruycheva',
            sport: 'rowing',
            games: 'montreal 1976',
            img: '../pics/stoyankagruycheva.jpg',
            all: 'all',
        },
        {
            champName: 'ekaterina dafovska',
            sport: 'biathlon',
            games: 'nagano 1998',
            img: '../pics/ekaterinadafovska.jpg',
            all: 'all',
        },
        {
            champName: 'stoyan delchev',
            sport: 'gymnastics',
            games: 'moscow 1980',
            img: '../pics/stoyandelchev.jpg',
            all: 'all',
        },
        {
            champName: 'dimitar dobrev',
            sport: 'wrestling',
            games: 'rome 1960',
            img: '../pics/dimitardobrev.jpg',
            all: 'all',
        },
        {
            champName: 'milen dobrev',
            sport: 'weightlifting',
            games: 'athens 2004',
            img: '../pics/milendobrev.jpg',
            all: 'all',
        },
        {
            champName: 'yordanka donkova',
            sport: 'athletics',
            games: 'seoul 1988',
            img: '../pics/yordankadonkova.jpg',
            all: 'all',
        },
        {
            champName: 'simona dyankova',
            sport: 'rhythmic gimnastics',
            games: 'tokyo 2020',
            img: '../pics/simonadyankova.jpg',
            all: 'all',
        },
        {
            champName: 'erika zafirova',
            sport: 'rhythmic gimnastics',
            games: 'tokyo 2020',
            img: '../pics/erikazafirova.jpg',
            all: 'all',
        },
        {
            champName: 'asen zlatev',
            sport: 'weightlifting',
            games: 'moscow 1980',
            img: '../pics/asenzlatev.jpg',
            all: 'all',
        },
        {
            champName: 'ivan ivanov',
            sport: 'weightlifting',
            games: 'barcelona 1992',
            img: '../pics/ivanivanov.jpg',
            all: 'all',
        },
        {
            champName: 'hasan isaev',
            sport: 'wrestling',
            games: 'montreal 1976',
            img: '../pics/hasanisaev.jpg',
            all: 'all',
        },
        {
            champName: 'valentin yordanov',
            sport: 'wrestling',
            games: 'athlanta 1996',
            img: '../pics/valentinyordanov.jpg',
            all: 'all',
        },
        {
            champName: 'zdravka yordanova',
            sport: 'rowing',
            games: 'montreal 1976',
            img: '../pics/zdravkayordanova.jpg',
            all: 'all',
        },
        {
            champName: 'siyka kelbecheva',
            sport: 'rowing',
            games: 'montreal 1976',
            img: '../pics/siykakelbecheva.jpg',
            all: 'all',
        },
        {
            champName: 'petar kirov',
            sport: 'wrestling',
            games: 'mexico 1968',
            img: '../pics/petarkirov.jpg',
            all: 'all',
        },
        {
            champName: 'petar kirov',
            sport: 'wrestling',
            games: 'munich 1972',
            img: '../pics/petarkirov.jpg',
            all: 'all',
        },
        {
            champName: 'tanyu kiryakov',
            sport: 'shooting',
            games: 'seoul 1988',
            img: '../pics/tanyukiryakov.jpg',
            all: 'all',
        },
        {
            champName: 'tanyu kiryakov',
            sport: 'shooting',
            games: 'sydney 2000',
            img: '../pics/tanyukiryakov.jpg',
            all: 'all',
        },
        {
            champName: 'stefani kiryakova',
            sport: 'rhythmic gimnastics',
            games: 'tokyo 2020',
            img: '../pics/stefanikiryakova.jpg',
            all: 'all',
        },
        {
            champName: 'atanas komshev',
            sport: 'wrestling',
            games: 'seoul 1988',
            img: '../pics/atanaskomshev.jpg',
            all: 'all',
        },
        {
            champName: 'georgi kostadinov',
            sport: 'boxing',
            games: 'munich 1972',
            img: '../pics/georgikostadinov.jpg',
            all: 'all',
        },
        {
            champName: 'stefka kostadinova',
            sport: 'athletics',
            games: 'athlanta 1996',
            img: '../pics/stefkakostadinova.jpg',
            all: 'all',
        },
        {
            champName: 'stoyka krasteva',
            sport: 'boxing',
            games: 'tokyo 2020',
            img: '../pics/stoykakrasteva.jpg',
            all: 'all',
        },
        {
            champName: 'petar lesov',
            sport: 'boxing',
            games: 'moscow 1980',
            img: '../pics/petarlesov.jpg',
            all: 'all',
        },
        {
            champName: 'lyubomir lyubenov',
            sport: 'canoe',
            games: 'moscow 1980',
            img: '../pics/lyubomirlyubenov.jpg',
            all: 'all',
        },
        {
            champName: 'ivaylo marinov',
            sport: 'boxing',
            games: 'seoul 1988',
            img: '../pics/ivaylomarinov.jpg',
            all: 'all',
        },
        {
            champName: 'sevdalin marinov',
            sport: 'weightlifting',
            games: 'seoul 1988',
            img: '../pics/sevdalinmarinov.jpg',
            all: 'all',
        },
        {
            champName: 'tereza marinova',
            sport: 'athletics',
            games: 'sydney 2000',
            img: '../pics/terezamarinova.jpg',
            all: 'all',
        },
        {
            champName: 'hristo markov',
            sport: 'athletics',
            games: 'seoul 1988',
            img: '../pics/hristomarkov.jpg',
            all: 'all',
        },
        {
            champName: 'yordan mitkov',
            sport: 'weightlifting',
            games: 'montreal 1976',
            img: '../pics/yordanmitkov.jpg',
            all: 'all',
        },
        {
            champName: 'georgi markov',
            sport: 'wrestling',
            games: 'munich 1972',
            img: '../pics/georgimarkov.jpg',
            all: 'all',
        },
        {
            champName: 'armen nazaryan',
            sport: 'wrestling',
            games: 'sydney 2000',
            img: '../pics/armennazaryan.jpg',
            all: 'all',
        },
        {
            champName: 'rumyana neykova',
            sport: 'rowing',
            games: 'beijing 2008',
            img: '../pics/rumyananeykova.jpg',
            all: 'all',
        },
        {
            champName: 'andon nikolov',
            sport: 'weightlifting',
            games: 'munich 1972',
            img: '../pics/andonnikolov.jpg',
            all: 'all',
        },
        {
            champName: 'norair nurikyan',
            sport: 'weightlifting',
            games: 'munich 1972',
            img: '../pics/norairnurikyan.jpg',
            all: 'all',
        },
        {
            champName: 'norair nurikyan',
            sport: 'weightlifting',
            games: 'montreal 1976',
            img: '../pics/norairnurikyan.jpg',
            all: 'all',
        },
        {
            champName: 'svetla ocetova',
            sport: 'rowing',
            games: 'montreal 1976',
            img: '../pics/svetlaocetova.jpg',
            all: 'all',
        },
        {
            champName: 'daniel petrov',
            sport: 'boxing',
            games: 'athlanta 1996',
            img: '../pics/danielpetrov.jpg',
            all: 'all',
        },
        {
            champName: 'boyan radev',
            sport: 'wrestling',
            games: 'tokyo 1964',
            img: '../pics/boyanradev.jpg',
            all: 'all',
        },
        {
            champName: 'boyan radev',
            sport: 'wrestling',
            games: 'mexico 1968',
            img: '../pics/boyanradev.jpg',
            all: 'all',
        },
        {
            champName: 'madlen radukanova',
            sport: 'rhythmic gimnastics',
            games: 'tokyo 2020',
            img: '../pics/madlenradukanova.jpg',
            all: 'all',
        },
        {
            champName: 'georgi raykov',
            sport: 'wrestling',
            games: 'moscow 1980',
            img: '../pics/georgiraykov.jpg',
            all: 'all',
        },
        {
            champName: 'valentin raychev',
            sport: 'wrestling',
            games: 'moscow 1980',
            img: '../pics/valentinraychev.jpg',
            all: 'all',
        },
        {
            champName: 'yanko rusev',
            sport: 'weightlifting',
            games: 'moscow 1980',
            img: '../pics/yankorusev.jpg',
            all: 'all',
        },
        {
            champName: 'yanko rusev',
            sport: 'weightlifting',
            games: 'melbourne 1956',
            img: '../pics/nikolastanchev.jpg',
            all: 'all',
        },
        {
            champName: 'laura traats',
            sport: 'rhythmic gimnastics',
            games: 'tokyo 2020',
            img: '../pics/lauratraats.jpg',
            all: 'all',
        },
        {
            champName: 'ivanka hristova',
            sport: 'athletics',
            games: 'montreal 1976',
            img: '../pics/ivankahristova.jpg',
            all: 'all',
        },
    ]
}

export default champions;